server:
  port: 8082

spring:
  application:
    name: shop-server
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.22.158:8848
        namespace: zhuduole
      config:
        server-addr: 47.100.22.158:8848
        namespace: zhuduole
        file-extension: yaml
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:F:/ssd/b2c_mall/shop/shop.db?foreign_keys=on
  redis:
    host: 47.100.22.158
    port: 6379
    database: 0
    timeout: 5000

mybatis:
  configuration:
    map-underscore-to-camel-case: true